export enum PermissionsEnum {
    "CREATE_PERMISSION" = "CREATE_PERMISSION",
    "GET_PERMISSION_BY_ID" = "GET_PERMISSION_BY_ID",
    "GET_PERMISSIONS" = "GET_PERMISSIONS",
    "UPDATE_PERMISSION_BY_ID" = "UPDATE_PERMISSION_BY_ID",
    "DELETE_PERMISSION_BY_iD" = "DELETE_PERMISSION_BY_iD"
}